template = "https://github.com/giellalt/template-lang-und"
rev_id = 292
template_sha = "ae713c1306873a265055417badc511956629639d"

[replacements]
__GLOTTOLOG_ID__ = "inup1234"
__REPO__ = "lang-ipk"
__UND2C__ = "ik"
__UNDEFINED__ = "Inupiaq"
__UND__ = "ipk"
